(MWEB-166) 사용자는 아두이노 우노 이외에도 다른 아두이노 보드에서 확장 모듈을 모두 사용할 수 있다
EXIT-MAKE/MakeWebBlockEditor pull request #86
Opened 2021-11-11 07:38 UTC by oh930428

## What does this PR do?
1. 디볼트로 되어져 있는 디바이스 이름 Select Device -> arduinoUno로 변경
2. arduinoMini 관련 삭제
3. 디볼트 블록으로 핀블록의 기준을 디바이스 arduinoUno에서 디바이스 타입 arduino 로 변경 
4. arduinoLeonardo에 extention block 추가
5. arduinoNano에 extention block 추가
6. arduinoMega2560에 extention block 추가
7. arduinoEsp32에 extention block 추가
8. arduinoEsp8266에 extention block 추가
9.  arduino_gyro_sensor_gyro text code 수정 
10. arduino_rotary_encoder_rotary_encoder text code 수정

## Related links
- Jira: https://make-web.atlassian.net/browse/MWEB-166

2021-11-11 09:20 UTC, jinwook4217 requested changes

2021-11-11 09:20 UTC, jinwook4217 commented on src/desktop/reducers/device.js
> +  deviceName: 'Arduino Uno',
기본값 Select Device를 왜 다시 Arduino Uno로 바꾸는 이유는 무엇인가요?
이전에 처음에 디바이스를 선택하지 않았는데도 Arduino Uno가 떠있어서 바꿔달라고 요청한 기억이 있습니다

2021-11-11 09:20 UTC, jinwook4217 commented on extensions/openblock-blocks/generators/arduino/arduino.js
>      `AF_DCMotor motor_${motor}(${motor})`,
generator 코드는 제가 리팩토링 하면서 수정한 부분이 있어서 수정 취소 해주시면 될 것 같습니다!

2021-11-11 09:45 UTC, jinwook4217 reviewed
기본값 Select Device를 왜 다시 Arduino Uno로 바꾸는 이유는 무엇인가요?
이전에 처음에 디바이스를 선택하지 않았는데도 Arduino Uno가 떠있어서 바꿔달라고 요청한 기억이 있습니다

2021-11-11 09:49 UTC, jinwook4217 approved these changes

2021-11-12 04:22 UTC, opal2020 commented
![image](https://user-images.githubusercontent.com/54465981/141408986-47a2dc99-994b-4d3b-a631-c6d9e8f6b3ae.png)
MakeyMakey 디바이스에서 핀블럭들은 영어버전으로 뜹니다

2021-11-12 04:24 UTC, opal2020 commented
![image](https://user-images.githubusercontent.com/54465981/141409175-256bd6ce-7a44-48aa-8654-ac17fd5cb8a1.png)
마이크로비트 카테고리들에 이미지가 없습니다

2021-11-12 04:27 UTC, opal2020 commented
![image](https://user-images.githubusercontent.com/54465981/141409368-b8549cdd-0cac-46a3-8807-839160086d84.png)
마이크로비트 정체를 알 수 없는 블럭..! 마이크로비트 버전투도 마찬가지입니다

2021-11-12 04:44 UTC, opal2020 commented
https://user-images.githubusercontent.com/54465981/141410004-b735741c-c54b-41c1-95b5-f38107a8832d.mp4

카테고리를 선택 후 디바이스를 변경하면 라이브러리에 해당 카테고리가 그대로 남아있는 이슈,, 이건 따로 브랜치를 파서 해결해야 할 것 같습니다

2021-11-12 05:10 UTC, oh930428 commented
지금 현재 주신 프리뷰들 다른 브랜치가 머지가되면 해결 될 것같습니다

2021-11-12 06:00 UTC, opal2020 commented
어떤 브랜치를 말씀하시는 걸까요? 잭이 올리신 브랜치 말씀하시는 건가요?

2021-11-12 08:38 UTC, opal2020 requested changes
![image](https://user-images.githubusercontent.com/54465981/141436616-959dd6ca-b0ad-4f91-85a1-08ef4e250de0.png)
마이크로비트 함수 에러 있습니다 (버전2도 마찬가지)

2021-11-22 10:07 UTC, jinwook4217 commented
@opal2020 체리 이거 머지해도 되지 않을까요??

2021-11-23 06:52 UTC, jinwook4217 approved these changes
LGTM

2021-11-23 06:55 UTC, opal2020 approved these changes

2021-11-23 07:06 UTC, merged